### ISSUE TITLE
"java.lang.NoClassDefFoundError: Could not initialize class" on paper 1.18.2

### ISSUE THREAD

**Issue by nhanledev** [aematsubara/InventoryUpdate#1]
Hello,

Thank you for an amazing library.

On the update of Paper 1.18.2, the lib is now broken because the server just throw `java.lang.NoClassDefFoundError` and refuses to run the code further.

This library still works on Paper 1.18.1 and 1.17.1 so I think someone need to take a look at the static initiation to fix it.

I only call `InventoryUpdate.updateInventory(Plugin Instance, Player, PlaceholderAPI.setPlaceholders(player, "My new title"));` 

I am using the latest version of ReflectionUtils to this date of post, which is `8.7.0` and it states to support 1.18.2.

**Comment by aematsubara** [comment]
Hi! Can you show the whole stacktrace please?

**Comment by nhanledev** [comment]
Hi, this is my full stack trace, I think something changed in 1.18.2 because it still works in older build of paper. I encountered this bug on paper 1.18.2 build 267

```
[11:15:33 WARN]: java.lang.IllegalArgumentException: Can not set final int field net.minecraft.world.inventory.Container.j to java.lang.Boolean
[11:15:33 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[11:15:33 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[11:15:33 WARN]:        at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
[11:15:33 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.getInt(UnsafeQualifiedIntegerFieldAccessorImpl.java:58)
[11:15:33 WARN]:        at java.base/jdk.internal.reflect.UnsafeQualifiedIntegerFieldAccessorImpl.get(UnsafeQualifiedIntegerFieldAccessorImpl.java:38)
[11:15:33 WARN]:        at java.base/java.lang.reflect.Field.get(Field.java:425)
[11:15:33 WARN]:        at RandomBox.jar//me.mybox.util.InventoryUpdate.updateInventory(InventoryUpdate.java:137)
[11:15:33 WARN]:        at RandomBox.jar//me.mybox.gui.view.GuiView.tickNotStopped(GuiView.java:112)
[11:15:33 WARN]:        at RandomBox.jar//me.mybox.gui.view.GuiView.run(GuiView.java:85)
[11:15:33 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[11:15:33 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[11:15:33 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1531)
[11:15:33 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[11:15:33 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
[11:15:33 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[11:15:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[11:15:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by aematsubara** [comment]
I forgot that I used this resource in my Roulette plugin and I already updated this to 1.18.2, I'll update ASAP

**Comment by nhanledev** [comment]
Yes I saw one issue on your Roulette plugin which is the same issue, thank you <3

**Comment by aematsubara** [comment]
Updated, let me know if I'ts working so I can close this issue :)

**Comment by nhanledev** [comment]
Hello aematsubara, the update works very well!! Thank you for the quick fix <3
